name: cuncunapp
description: A new Flutter project.
version: 3.0.1+30000002

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.0
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
